#!/bin/bash

. ../env.sh

set -x

sycl-ls
export SYCL_DEVICE_SELECTOR=level_zero:gpu

dir=profile.$(date +%Y%m%d%H%M%S)
mkdir -p $dir
cp lj.cpp Makefile profiler.hpp $dir/.
cd $dir
make -B
root=$(pwd)
EXE="../lj -N $NUM_PARTICLE -e 1000 -s 1000"

mkdir aps
cd aps
#aps --start-paused --result-dir=./aps_result -- $EXE &> aps.log
#aps --report -H aps.html ./aps_result &> aps_report.log

cd $root
mkdir advisor
cd advisor
advi_dir=./advi_results
ADVISOR="advisor --project-dir=$advi_dir" # -knob sampling-interval=1"
#$ADVISOR --collect=roofline --profile-gpu                        -- $EXE &> advi_roofline.log
#$ADVISOR --collect=projection --profile-gpu --model-baseline-gpu -- $EXE &> advi_projection.log

cd $root
mkdir vtune
cd vtune
VTUNE="vtune --start-paused -knob sampling-mode=hw"
$VTUNE -collect gpu-hotspots          $EXE &> gpu-hotspots.log
