#!/bin/bash

. ../env.sh

set -x

dir=profile.$(date +%Y%m%d%H%M%S)
mkdir -p $dir
cp lj.cpp Makefile profiler.hpp $dir/.
cd $dir
make -B
root=$(pwd)
EXE="../lj -N $NUM_PARTICLE -e 1000 -s 1000"

mkdir aps
cd aps
aps --start-paused --result-dir=./aps_result -- $EXE &> aps.log
aps --report -H aps.html ./aps_result &> aps_report.log

cd $root
mkdir advisor
cd advisor
advi_dir=./advi_results
#ADVISOR="advisor --collect=roofline --enable-cache-simulation --project-dir=$advi_dir -- "
#$ADVISOR $EXE &> advi_roofline.log
advisor --collect=survey                                             --project-dir=$advi_dir -- $EXE &> advi_survery.log
advisor --collect=tripcounts -flop -stacks --enable-cache-simulation --project-dir=$advi_dir -- $EXE &> advi_tripcounts.log
advisor --collect=offload                                            --project-dir=$advi_dir -- $EXE &> advi_survery.log
advisor --report=roofline --project-dir=$advi_dir --report-output=./advi_roofline.html
advisor --report=offload  --project-dir=$advi_dir --report-output=./advi_offload.html

exit

cd $root
mkdir vtune
cd vtune
VTUNE="vtune --start-paused"
$VTUNE -collect hotspots          $EXE &> hotspots.log
$VTUNE -collect hpc-performance   $EXE &> hpc-performance.log
$VTUNE -collect uarch-exploration $EXE &> uarch-exploration.log
